TrajectoryPlannerROS:

  holonomic_robot: false
  meter_scoring: true
  max_vel_x: 0.3 
  min_vel_x: -0.3
  max_vel_theta: 1.75
  min_vel_theta: -1.75
  acc_lim_x: 0.6 
  acc_lim_y: 0.6 
  acc_lim_theta: 0.7
  yaw_goal_tolerance: 0.5
  sim_time: 3.0
