map_type: costmap
obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.1175, -0.17], [-0.1175, 0.17], [0.1175, 0.17], [0.1175, -0.17]]
inflation_radius: 0.5
transform_tolerance: 0.5
observation_sources: laser_scan_sensor point_cloud_sensor
laser_scan_sensor: { sensor_frame: laser,  data_type: LaserScan, topic: scan, marking: true, clearing: true, min_obstacle_height : 0.0}
point_cloud_sensor: {sensor_frame: camera_link, data_type: PointCloud2, topic: camera/depth/color/points, marking: true, clearing: true, min_obstacle_height: 0.1}


