global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 2
   publish_frequency: 2
   width: 40.0
   height: 40.0
   resolution: 0.05
   static_map: true
   rolling_window: false
   transform_tolerance: 0.5

