local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 1
   publish_frequency: 2
   static_map: false
   rolling_window: true
   width: 2.5 
   height: 2.5
   inflation_radius: 0.5
   resolution: 0.05
   rolling_window: true
   transform_tolerance: 0.5



  
