version: '3.7'

services:

  robot_imu:
    network_mode: host
    environment:
        - ROS_MASTER_URI=http://nvidia:11311 
    image: ubuntu-melodic/ros:robot-imu
    container_name: robot_imu 

  ros_vo:
    network_mode: host
    environment:
        - ROS_MASTER_URI=http://nvidia:11311 
    image: ubuntu-melodic/ros:ros-vo
    container_name: ros_vo 

  robot_navigation:
    network_mode: host
    environment:
        - ROS_MASTER_URI=http://nvidia:11311 
    image: ubuntu-melodic/ros:robot-navigation
    container_name: robot_navigation 

